pipeline:
  docker:
    image: plugins/docker
    dockerfile: Dockerfile
    insecure : true
    registry: dronetest.home.dyndns.org:5000
    repo: dronetest.home.dyndns.org:5000/test
    tag: lastest